name: Test installation

on:
  pull_request:
    branches:
    - master

jobs:
# -----------------------------------------
#    Install with pip
# -----------------------------------------
  install_with_pip:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install batchflow with pip
      run: |
        pip install --user -U pip 
        pip install wheel
        echo ${{ github.event.repository.full_name }}
        echo ${{ github.event.pull_request.head.repo.full_name }}
        echo ${{pull_request.repository.owner}}
#        pip install -e git+https://github.com/${{ github.event.repository.full_name }}.git@${{ github.head_ref }}#egg=batchflow
